package Cliente;

import Server.Jogador;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author gabriel
 */
public class GamePanel extends javax.swing.JFrame implements Runnable {

    Player player;
    //Player player2; //
    static List<Player> players = new ArrayList<>();

    String host = "127.0.0.1";
    int porta = 8020;

    Socket s;
    BufferedReader in;
    PrintWriter out;

    Boolean keyRight = false, keyLeft = false, keyUp = false, keyDown = false, keySpace = false;
    Thread t;
    Integer speed = 7;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                formKeyPressed(evt);
            }

            public void keyReleased(KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_RIGHT:
                keyRight = true;
                enviarMensagem("r");
                //player.setIconRight();
                break;
            case KeyEvent.VK_LEFT:
                keyLeft = true;
                enviarMensagem("l");
                //player.setIconLeft();
                break;
            case KeyEvent.VK_UP:
                keyUp = true;
                enviarMensagem("u");
                break;
            case KeyEvent.VK_DOWN:
                keyDown = true;
                enviarMensagem("d");
                break;
            case KeyEvent.VK_SPACE:
                keySpace = true;
                enviarMensagem("s");
                //player.setIconSpace();
                break;
        }

    }//GEN-LAST:event_formKeyPressed


    public void enviarMensagem(String msg) { //mexer //talvez deixar como thread!
        out.println(msg);
        out.flush();
        //System.out.println(msg);
    }

    public void receberMensagens() { //(transformar em Thread)
        new Thread(() -> {
            try {
                try {
                    String msg;
                    while ((msg = in.readLine()) != null) {
                        System.out.println(msg);
                        if (msg.indexOf('-') >= 0) {
                            if (GamePanel.players.size() >= 2) {
                                String[] string = msg.split("-");
                                String[] jogadorA = string[0].split(":");
                                String[] jogadorB = string[1].split(":");

                                players.get(0).setBounds(Integer.parseInt(jogadorA[0]), (Integer.parseInt(jogadorA[1])), 90, 127);
                                players.get(1).setBounds(Integer.parseInt(jogadorB[0]), (Integer.parseInt(jogadorB[1])), 90, 127);

                            } else {
                                if (GamePanel.players.size() == 1) {
                                    player = new Player();
                                    player.setup(); //configura o player.
                                    getContentPane().add(player);
                                    repaint();
                                    player.setIconStopped();
                                    players.add(player); //

                                } else {
                                    if (GamePanel.players.size() == 0) {

                                        player = new Player();
                                        player.setup(); //configura o player.
                                        getContentPane().add(player);
                                        repaint();
                                        player.setIconStopped();
                                        players.add(player); //
                                    }
                                }
                            }
                        } else {
                            if (GamePanel.players.size() == 0) {

                                player = new Player();
                                player.setup(); //configura o player.
                                getContentPane().add(player);
                                repaint();
                                player.setIconStopped();
                                players.add(player); //

                            }
                            String[] separado = msg.split(":");
                            players.get(0).setBounds(Integer.parseInt(separado[0]), (Integer.parseInt(separado[1])), 90, 127);
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }).start();
    }

    private void formKeyReleased(KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_RIGHT:
                keyRight = false;
                player.setIconStopped();
                break;
            case KeyEvent.VK_LEFT:
                keyLeft = false;
                player.setIconStopped();
                break;
            case KeyEvent.VK_UP:
                keyUp = false;
                player.setIconStopped();
                break;
            case KeyEvent.VK_DOWN:
                keyDown = false;
                player.setIconStopped();
                break;
            case KeyEvent.VK_SPACE:
                keySpace = false;
                player.setIconStopped();
                break;
        }
    }//GEN-LAST:event_formKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened   //////
        // TODO add your handling code here:
        try {
            s = new Socket(host, porta);
            in = new BufferedReader(new InputStreamReader(s.getInputStream()));
            out = new PrintWriter(s.getOutputStream());

            receberMensagens();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GamePanel g = new GamePanel();
                g.setSize(800, 600);
                g.setResizable(false);
                g.setVisible(true);

            }
        });
    }

    @Override
    public void run() {
        while (true) {
            try {


            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
